coordinate_system: reference_image
crowd_sim:
  agent_groups:
    - {agents_name: [deliveryRobot1, deliveryRobot2], agents_number: 2, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.40000000000000002, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: L1_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.10000000000000001
graphs:
  {}
levels:
  L1:
    drawing:
      filename: depot_scan.png
    elevation: 0
    lanes:
      - [21, 15, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [22, 16, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_1], orientation: [1, ""], speed_limit: [3, 0]}]
      - [23, 17, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_2], orientation: [1, ""], speed_limit: [3, 0]}]
      - [24, 18, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_3], orientation: [1, ""], speed_limit: [3, 0]}]
      - [25, 19, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_6], orientation: [1, ""], speed_limit: [3, 0]}]
      - [26, 20, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_5], orientation: [1, ""], speed_limit: [3, 0]}]
      - [30, 24, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_3], orientation: [1, ""], speed_limit: [3, 0]}]
      - [29, 23, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_2], orientation: [1, ""], speed_limit: [3, 0]}]
      - [28, 22, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_1], orientation: [1, ""], speed_limit: [3, 0]}]
      - [28, 32, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [32, 29, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [29, 33, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [33, 30, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [24, 34, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [34, 23, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [23, 35, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [35, 22, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [22, 36, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [25, 37, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [37, 26, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [26, 38, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [38, 27, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [21, 36, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [27, 39, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [27, 40, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_4], orientation: [1, ""], speed_limit: [3, 0]}]
      - [25, 41, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_6], orientation: [1, ""], speed_limit: [3, 0]}]
      - [41, 30, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [39, 46, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [27, 45, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_4], orientation: [1, ""], speed_limit: [3, 0]}]
      - [45, 28, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [29, 43, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [46, 31, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [31, 36, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [43, 26, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, workcell_5], orientation: [1, ""], speed_limit: [3, 0]}]
      - [45, 44, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [44, 43, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [43, 42, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [42, 41, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [31, 47, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [47, 28, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [46, 48, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [48, 45, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [14, 39, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [49, 50, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 1], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [52, 51, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 2], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
    layers:
      {}
    measurements:
      - [0, 1, {distance: [3, 30.199999999999999]}]
    vertices:
      - [0.104, 307.17000000000002, 0, ""]
      - [604.029, 307.00799999999998, 0, ""]
      - [2.0099999999999998, 1.994, 0, ""]
      - [602.91899999999998, 1.0029999999999999, 0, ""]
      - [603.96900000000005, 301.74000000000001, 0, ""]
      - [1.7090000000000001, 304.33499999999998, 0, ""]
      - [147.125, 72.120000000000005, 0, ""]
      - [157.90799999999999, 72.030000000000001, 0, ""]
      - [158.08799999999999, 82.813999999999993, 0, ""]
      - [146.76499999999999, 82.903999999999996, 0, ""]
      - [147.178, 222.09899999999999, 0, ""]
      - [158.00399999999999, 222.04900000000001, 0, ""]
      - [158.05500000000001, 233.12899999999999, 0, ""]
      - [147.02600000000001, 233.02699999999999, 0, ""]
      - [225.309, 46.283999999999999, 0, deliveryRobotCharger1, {is_charger: [4, true], is_holding_point: [4, true], is_parking_spot: [4, true], spawn_robot_name: [1, deliveryRobot1], spawn_robot_type: [1, DeliveryRobot]}]
      - [240.38200000000001, 284.73700000000002, 0, deliveryRobotCharger2, {is_charger: [4, true], is_holding_point: [4, true], is_parking_spot: [4, true], spawn_robot_name: [1, deliveryRobot2], spawn_robot_type: [1, DeliveryRobot]}]
      - [180.55500000000001, 208.523, 0, workcell_1, {dropoff_ingestor: [1, workcell_1], is_holding_point: [4, false], is_parking_spot: [4, false], mutex: [1, workcell_1], pickup_dispenser: [1, workcell_1]}]
      - [120.56100000000001, 208.73599999999999, 0, workcell_2, {dropoff_ingestor: [1, workcell_2], is_holding_point: [4, false], is_parking_spot: [4, false], mutex: [1, workcell_2], pickup_dispenser: [1, workcell_2]}]
      - [60.567999999999998, 208.94900000000001, 0, workcell_3, {dropoff_ingestor: [1, workcell_3], mutex: [1, workcell_3], pickup_dispenser: [1, workcell_3]}]
      - [60.780999999999999, 98.109999999999999, 0, workcell_6, {dropoff_ingestor: [1, workcell_6], mutex: [1, workcell_6], pickup_dispenser: [1, workcell_6]}]
      - [120.56100000000001, 98.748000000000005, 0, workcell_5, {dropoff_ingestor: [1, workcell_5], mutex: [1, workcell_5], pickup_dispenser: [1, workcell_5]}]
      - [225.733, 250.20699999999999, 0, ""]
      - [180.64599999999999, 186.441, 0, "", {is_holding_point: [4, false], is_passthrough_point: [4, true], mutex: [1, workcell_1]}]
      - [120.56100000000001, 186.36099999999999, 0, "", {is_holding_point: [4, false], is_passthrough_point: [4, true], mutex: [1, workcell_2]}]
      - [60.612000000000002, 186.28, 0, "", {mutex: [1, workcell_3]}]
      - [60.738999999999997, 120.01300000000001, 0, "", {mutex: [1, workcell_6]}]
      - [120.56100000000001, 120.009, 0, "", {mutex: [1, workcell_5]}]
      - [180.92099999999999, 120.005, 0, "", {mutex: [1, workcell_4]}]
      - [180.74100000000001, 163.51900000000001, 0, "", {is_holding_point: [4, false], is_passthrough_point: [4, true], mutex: [1, workcell_1]}]
      - [120.56100000000001, 163.506, 0, "", {is_holding_point: [4, false], is_passthrough_point: [4, true], mutex: [1, workcell_2]}]
      - [60.655000000000001, 163.49299999999999, 0, "", {mutex: [1, workcell_3]}]
      - [225.553, 163.52799999999999, 0, "", {is_holding_point: [4, false]}]
      - [152.36799999999999, 163.51300000000001, 0, "", {is_holding_point: [4, true]}]
      - [90.802999999999997, 163.5, 0, "", {is_holding_point: [4, true]}]
      - [89.682000000000002, 186.31899999999999, 0, "", {is_holding_point: [4, true]}]
      - [149.965, 186.40000000000001, 0, "", {is_holding_point: [4, true]}]
      - [225.601, 186.5, 0, "", {is_holding_point: [4, false]}]
      - [91.251999999999995, 120.011, 0, "", {is_holding_point: [4, true]}]
      - [151.595, 120.00700000000001, 0, "", {is_holding_point: [4, true]}]
      - [225.46199999999999, 120.001, 0, ""]
      - [181.011, 98.334999999999994, 0, workcell_4, {dropoff_ingestor: [1, workcell_4], mutex: [1, workcell_4], pickup_dispenser: [1, workcell_4]}]
      - [60.697000000000003, 141.631, 0, "", {mutex: [1, workcell_6]}]
      - [90.257999999999996, 141.61500000000001, 0, "", {is_holding_point: [4, true]}]
      - [120.56100000000001, 141.59800000000001, 0, "", {mutex: [1, workcell_5]}]
      - [152.38900000000001, 141.58000000000001, 0, "", {is_holding_point: [4, true]}]
      - [180.83199999999999, 141.56399999999999, 0, "", {mutex: [1, workcell_4]}]
      - [225.50700000000001, 141.53899999999999, 0, ""]
      - [203.21899999999999, 163.523, 0, "", {is_holding_point: [4, true]}]
      - [202.70699999999999, 141.55199999999999, 0, "", {is_holding_point: [4, true]}]
      - [170.40899999999999, 207.85400000000001, 0, conveyor_1_workcell_1]
      - [130.899, 207.732, 0, conveyor_1_workcell_2]
      - [110.471, 207.976, 0, conveyor_2_workcell_2]
      - [70.594999999999999, 207.976, 0, conveyor_2_workcell_3]
lifts: {}
name: depot
