task:
  id: "31"
  type: "place_on_conveyor"
  payload: |
    {
      "processId": "place_on_conveyor",
      "name": "Pick and Place",
      "item": {
        "SkuId": "productA",
        "description": "productA",
        "unit": "dummy_unit",
        "quantity": 1.0,
        "quantityPerPallet": 1.0
      },
    }
